import type { LexData } from '../types.ts';

const r = String.raw;
const AP = r`(?<ap>morgens|vormittags|mittags|nachmittags|abends|nachts|pm)?`;

export const de: LexData = {
  code: 'de', script: 'latin', spaced: true,
  nums: { ein: 1, eins: 1, eine: 1, einen: 1, zwei: 2, drei: 3, vier: 4, fünf: 5, sechs: 6, sieben: 7, acht: 8, neun: 9, zehn: 10, elf: 11, zwölf: 12, fünfzehn: 15, zwanzig: 20, dreißig: 30, dreissig: 30 },
  today: r`heute(?: abend| morgen| nachmittag| nacht| früh)?`, tomorrow: 'morgen', dayafter: 'übermorgen', yesterday: 'gestern',
  weekdays: ['sonntag*', 'montag*', 'dienstag*', 'mittwoch*', 'donnerstag*', 'freitag*', r`samstag*|sonnabend*`],
  months: [r`januar|jänner`, 'februar', r`märz|maerz`, 'april', 'mai', 'juni', 'juli', 'august', 'september', 'oktober', 'november', 'dezember'],
  nextweek: r`(?:in der |die )?(?:nächste|naechste|kommende) woche`, thisweek: 'diese woche',
  every: r`jeden|jede|jedes|alle`,
  dayWord: 'tag|tage', weekWord: 'woche|wochen',
  inN: [r`in (?<n>{num}) (?<u>tagen?|wochen?|monaten?)`],
  unitDay: 'tag*', unitWeek: 'woche*', unitMonth: 'monat*',
  dates: [r`(?:am |den |für den )?(?<d>\d{1,2})\.?\s*{mo}(?: \d{4})?`],
  time: [
    r`(?:um|gegen|ab|so um) (?<h>{num})(?::|\.)(?<m>\d{2})\s*(?:uhr)?\s*${AP}`,
    r`(?:um|gegen) halb (?<hb>{num})\s*${AP}`,
    r`(?:um|gegen) (?<qa>viertel nach) (?<h>{num})\s*${AP}`,
    r`(?:um|gegen) (?<qb>viertel vor) (?<h>{num})\s*${AP}`,
    r`(?:um|gegen|ab|so um) (?<h>{num})\s*(?:uhr)?\s*${AP}`,
    r`(?<h>\d{1,2})(?::|\.)(?<m>\d{2})\s*uhr`,
    r`(?<h>\d{1,2})\s*uhr\s*(?<m>\d{2})?`,
    r`(?<h>\d{1,2})\s*(?<ap>pm)`,
  ],
  range: [r`(?:von|zwischen) (?<h1>\d{1,2})(?:[:.](?<m1>\d{2}))?\s*(?:uhr)?\s*(?:bis|und|-)\s*(?<h2>\d{1,2})(?:[:.](?<m2>\d{2}))?\s*(?:uhr)?`],
  dur: [r`(?:für|dauer|eine dauer von|ca\.?) (?<n>{num}|\d+(?:[.,]\d+)?)\s*(?<u>stunden?|std|h|minuten?|min)`],
  unitHour: 'stunde*|std|h', unitMin: 'minute*|min',
  halfHour: r`(?:für )?eine halbe stunde|halbe stunde`, oneHour: r`für eine stunde|eine stunde lang`,
  pm: r`nachmittags|abends|nachts|pm`, am: r`morgens|vormittags|früh|frueh`,
  noon: r`mittags|mittag`, midnight: 'mitternacht',
  hintMorning: r`morgens|vormittags|am morgen|vormittag|früh|frueh|in der früh`, hintAfternoon: r`nachmittags|am nachmittag|nachmittag`, hintEvening: r`abends|am abend|abend|nachts`,
  c: {
    polite: r`bitte|könntest du|kannst du|könnten sie|können sie|ich möchte|ich will|ich brauche|ich muss|sag mir|hey|doch|gerne|ich habe|habe|hab`,
    add: r`füge*|hinzu|hinzufügen|trag*|eintragen|erstelle*|erstellen|anlegen|lege*|neue|neuer|neues|neu|notiere*|buche*|vereinbare*|plane*|speichere*|erinnere mich an|erinnere mich daran`,
    del: r`lösche*|löschen|entferne*|streiche*|storniere*|absagen|sage* ab|entfernen|streichen|loesch*`,
    move: r`verschieb*|verleg*|schiebe*|umbuchen|vorverlegen|aufschieben|ändere die (?:uhrzeit|zeit)|ändere den tag`,
    done: r`erledigt|fertig|abgeschlossen|geschafft|hake* ab|abhaken|markiere* (?:als )?(?:erledigt|fertig)|ist fertig|bin fertig mit`,
    show: r`zeige*|zeig mir|zeigen|sag mir|nenne*|liste*|gib mir|was sind|welche|anzeigen|schau*|ansehen|sieh*`,
    open: r`öffne*|öffnen|gehe zu|geh zu|gehe auf|geh auf|bring mich zu`,
    rename: r`benenne* um|umbenennen|benenne|ändere den (?:namen|titel)(?: von)?`,
    share: r`teile*|teilen|sende*|schicke*|schick|freigeben|gib frei`,
    mark: r`markiere*|setze*|stelle*|mach*`,
    plan: r`plane*|organisiere*|fülle*|ordne*|arrangiere*`,
    write: r`schreibe*|notiere*|speichere*|erstelle*|halte fest|merke*`,
    on: r`aktiviere*|schalte* ein|einschalten|schalte an|anschalten|erlaube*|aktivieren`,
    off: r`deaktiviere*|schalte* aus|ausschalten|stelle* ab|abschalten|stumm|blockiere*|deaktivieren`,
    undo: r`^(?:rückgängig|mach das rückgängig|rückgängig machen|zurück|widerrufe|widerrufen|abbrechen|storniere das|nicht so|letzte aktion rückgängig|undo)$`,
    task: r`aufgabe*|todo|to do|to-do|erledigung*|besorgung`,
    event: r`termin*|meeting*|besprechung*|treffen|sitzung*|anruf|telefonat*|videocall|training|workout|vorstellungsgespräch|gespräch|besuch|abendessen|mittagessen|essen|unterricht|kurs|arzttermin|verabredung|veranstaltung|ereignis`,
    cal: r`plan|kalender|agenda|terminkalender|zeitplan`,
    note: r`notiz*|memo|vermerk`,
    goal: r`ziel*`,
    mood: r`stimmung|laune`,
    finance: r`finanz*|ausgaben|geld|budget|erspar*|konto|konten`,
    health: r`gesundheit|schlaf|schritte|wohlbefinden`,
    sleepQ: r`wie (?:habe ich|hab ich) geschlafen|wie lange (?:habe ich|hab ich) geschlafen|wie war mein schlaf`,
    free: r`frei*|zeitfenster|lück*|verfügbar*|wann habe ich zeit|wann kann ich|freie zeit`,
    notif: r`benachrichtigung*|mitteilung*|push`,
    profile: r`profil|konto`,
    priv: 'privat*',
    pub: r`öffentlich*|public`,
    photo: r`foto|bild|profilbild`,
    dark: r`dunkel*|dark|nacht`,
    light: r`hell*|light|tag`,
    themeN: r`modus|design|thema|mode`,
    month: 'monat*',
    week: 'woche*',
    dayN: r`tag|tagesplan`,
    urgent: r`(?:als )?dringend*|eilig*`,
    important: r`(?:als )?wichtig*`,
    spent: r`wie ?viel (?:habe ich|hab ich) (?:ausgegeben|gespart|verdient)|wie ?viel gebe ich aus`,
    nowQ: r`was (?:soll|muss|sollte|kann) ich (?:jetzt|zuerst|als erstes|als nächstes)(?: tun| machen)?|was (?:soll|muss|sollte|kann) ich (?:jetzt )?(?:tun|machen)|was mache ich jetzt|womit (?:fange|soll ich) ich an|wo fange ich an|meine priorität|was ist (?:meine )?(?:nächste|wichtigste) aufgabe|was jetzt`,
    qHave: r`was habe ich|was steht an|was ist geplant|was liegt an|welche termine habe ich|was habe ich vor|habe ich termine`,
    qWhen: r`wann (?:ist|habe ich|beginnt|startet)|um wie viel uhr (?:ist|habe ich)|wie spät ist`,
    due: r`fälligkeit|frist|fällig|abgabe|bis spätestens`,
    workhours: r`arbeitszeit*|arbeitszeiten|bürozeiten|ich arbeite von`,
    briefing: r`tagesübersicht|tageszusammenfassung|zusammenfassung des tages|wie sieht mein tag aus|was erwartet mich heute|briefing|tagesrückblick`,
    resched: r`(?:plane|verschiebe)? ?(?:die )?(?:verpassten|ausgelassenen|versäumten) (?:sitzungen|aufgaben|sessions) neu(?: planen)?|verpasste (?:sitzungen|aufgaben) neu planen`,
    feel: r`ich fühle mich|mir ist|ich bin|heute bin ich|ich fühl mich|ich fühle`,
    into: r`in|zu|auf|als`,
    yes: r`^(?:ja|jawohl|okay|ok|klar|gerne|na klar|einverstanden|passt|genau|bestätigt|bestätige|mach das|sicher|stimmt)$`,
    no: r`^(?:nein|nee|nichts|vergiss es|lass es|lass gut sein|stopp|stop|doch nicht|nein danke)$`,
    choose: r`entscheide du|such du aus|wähl du|wie du willst|wie du meinst|wann du willst|wann es dir passt|wie es dir passt|du entscheidest|du darfst entscheiden|such aus`,
    apply: r`^(?:anwenden|übernehmen|bestätigen|bestätige|wende an|übernimm)$`,
    keepboth: r`^(?:beide behalten|beides behalten|behalte beide|behalte beides|beide|beides)$`,
    help: r`hilfe|was kannst du|was kannst du tun|befehle|beispiele|wie funktionierst du|wie funktioniert das`,
    hello: r`^(?:hallo|hi|hey|guten morgen|guten tag|guten abend|servus|moin|gru(?:ss|ß) dich)$`,
    thanks: r`^(?:danke|danke schön|vielen dank|dankeschön|super danke|prima)$`,
  },
  pages: {
    home: r`startseite|home|start`, plan: r`plan|kalender|agenda`, tasks: 'aufgaben', notes: 'notizen', health: 'gesundheit', finance: r`finanzen|geld`, travel: 'reisen',
    network: r`arbeit|netzwerk|jobs`, profile: 'profil', settings: 'einstellungen', mood: r`stimmung|laune`, messages: 'nachrichten', notifications: r`benachrichtigungen|mitteilungen`,
    stocks: r`aktien|börse`, portfolio: r`portfolio|depot`, taxes: 'steuern', forecast: 'prognose', chat: 'chat',
  },
  moods: {
    happy: r`glück*|froh*|zufrieden|gut|super|toll|fröhlich`, calm: r`ruhig|gelassen|entspannt|ausgeglichen`, neutral: r`neutral|normal|so la la`,
    stressed: r`gestresst|stress*|nervös|angespannt|ängstlich|besorgt|überfordert`, sad: r`traurig|niedergeschlagen|deprimiert|schlecht|bedrückt`, tired: r`müde|erschöpft|ausgelaugt`, angry: r`wütend|sauer|ärgerlich|verärgert|zornig`,
  },
  withP: r`(?:mit|an|für) (?<p>\p{L}[\p{L}'.-]*)`,
  edge: r`ein|eine|einen|einem|der|die|das|den|dem|des|zu|zum|zur|für|mit|auf|an|in|im|am|um|und|mein|meine|meinen|meinem|ich|mir|mich|dir|dich|bitte|noch|mal|hinzu|nach|von|bei|aus|als|bis`,
};
