import type { LexData } from '../types.ts';

const T = '(?:a las|a la|sobre las|hacia las|para las|alrededor de las|a eso de las)';
const AP = '(?<ap>de la manana|de la tarde|de la noche|de la madrugada|del mediodia|am|pm|a m|p m|a\\.m\\.|p\\.m\\.)?';

export const es: LexData = {
  code: 'es', script: 'latin', spaced: true,
  nums: { un: 1, uno: 1, una: 1, dos: 2, tres: 3, cuatro: 4, cinco: 5, seis: 6, siete: 7, ocho: 8, nueve: 9, diez: 10, once: 11, doce: 12, quince: 15, veinte: 20, treinta: 30 },
  today: 'hoy|esta noche|esta tarde|esta manana', tomorrow: 'manana', dayafter: 'pasado manana', yesterday: 'ayer',
  weekdays: ['domingo*', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado*'],
  months: ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre|setiembre', 'octubre', 'noviembre', 'diciembre'],
  nextweek: '(?:la )?semana (?:proxima|que viene|siguiente)|proxima semana', thisweek: 'esta semana',
  every: 'cada|todos los|todas las|todos',
  dayWord: 'dia|dias', weekWord: 'semana|semanas',
  inN: ['(?:dentro de|en) (?<n>{num}|un|una) (?<u>dias?|semanas?|meses|mes)'],
  unitDay: 'dia*', unitWeek: 'semana*', unitMonth: 'mes|meses',
  dates: ['(?:el |para el |dia )?(?<d>\\d{1,2}) (?:de )?{mo}(?: de \\d{4})?'],
  time: [
    `${T} (?<h>{num})(?::|\\.|h)(?<m>\\d{2})\\s*${AP}`,
    `${T} (?<h>{num}) y (?:(?<half>media)|(?<qa>cuarto))\\s*${AP}`,
    `${T} (?<h>{num}) menos (?<qb>cuarto)\\s*${AP}`,
    `${T} (?<h>{num})(?: horas?| en punto)?\\s*${AP}`,
    '(?<h>\\d{1,2})(?::(?<m>\\d{2}))?\\s*(?<ap>am|pm|a\\.m\\.|p\\.m\\.)',
    '(?<h>\\d{1,2}):(?<m>\\d{2})',
  ],
  range: [
    `(?:de|desde)(?: las)? (?<h1>\\d{1,2})(?::(?<m1>\\d{2}))?\\s*(?<ap1>am|pm)? (?:a|hasta)(?: las)? (?<h2>\\d{1,2})(?::(?<m2>\\d{2}))?\\s*(?<ap2>am|pm|de la tarde|de la noche|de la manana)?`,
  ],
  dur: [
    '(?:durante|por|de) (?<n>{num}|\\d+(?:[.,]\\d+)?) (?<u>horas?|h|minutos?|min)',
    '(?:durante|por) (?<n>{num}) (?<u>horas?)',
  ],
  unitHour: 'hora*|h', unitMin: 'minuto*|min',
  halfHour: '(?:durante |por )?media hora', oneHour: '(?:durante |por )?una hora',
  pm: 'pm|p m|p\\.m\\.|de la tarde|de la noche', am: 'am|a m|a\\.m\\.|de la manana|de la madrugada',
  noon: '(?:al )?mediodia', midnight: 'a?\\s?medianoche',
  hintMorning: 'por la manana|de la manana|en la manana|a la manana|esta manana', hintAfternoon: 'por la tarde|de la tarde|en la tarde|esta tarde', hintEvening: 'por la noche|de la noche|en la noche|esta noche',
  c: {
    polite: 'por favor|porfa|puedes|podrias|podria|quiero|quisiera|me gustaria|necesito|ayudame a|oye|hey|dime|vamos a',
    add: 'nuev[oa]|agrega*|anade*|anadir|anota*|apunta*|crea|crear|crea me|pon|ponme|poner|mete|inserta*|programa|programar|agendar|reserva*|incluye*|apunt[ae]me|recuerdame',
    del: 'elimina*|borra*|quita*|cancela*|suprime*|retira*|saca*|descarta*',
    move: 'mueve*|mover|muevelo|reprograma*|aplaza*|pospon*|posponer|adelanta*|traslada*|cambia(?:r)? (?:la |el )?(?:hora|dia|fecha|horario)|pasa(?:r)? (?:la|el)',
    done: 'termine|he terminado|he acabado|acabe|complete|he completado|completa|completado|hecho|marca(?:r)? (?:como )?(?:hech[oa]|complet\\p{L}+|terminad[oa])|tacha*|ya hice|ya termine|ya lo hice|ya esta hecho',
    show: 'muestra*|mostrar|dime|ensename|ver|cuales son|lista*|dame|enumera*|revisa*|consulta*|que (?:tareas|citas|reuniones|eventos)',
    open: 'abre|abrir|ve a|ir a|llevame a|vamos a|muestrame|entra en|abra',
    rename: 'renombra*|cambia(?:r)? (?:el )?(?:nombre|titulo)(?: de)?|cambiale el nombre',
    share: 'comparte*|compartir|envia*|manda*|mandale|enviale|muestrale',
    mark: 'marca*|pon|ponla|ponlo|establece*|configura*|haz|hazlo|define*|cambia a',
    plan: 'planifica*|organiza*|arregla*|rellena*|llena*|programa',
    write: 'escribe*|anota*|guarda*|toma|redacta*|apunta*|crea',
    on: 'activa*|enciende*|habilita*|prende*|pon',
    off: 'desactiva*|apaga*|deshabilita*|silencia*|bloquea*|quita',
    undo: '^(?:deshaz|deshacer|deshaz eso|cancela eso|cancela lo ultimo|anula|anular|anula eso|vuelve atras|revierte|revertir|atras|cancelar eso)$',
    task: 'tarea*|pendientes?|por hacer|to do|quehacer*|actividad*',
    event: 'reunion*|cita*|evento*|llamada*|junta*|videollamada*|compromiso*|entrenamiento|entrevista|visita|cena|almuerzo|comida|clase|consulta',
    cal: 'mi plan|el plan|plan|calendario|agenda|horario|cronograma|mi agenda|mi calendario',
    note: 'nota*|apunte*|memo|memorando',
    goal: 'objetivo*|meta*',
    mood: 'animo|estado de animo|humor',
    finance: 'finanza*|gastos?|dinero|presupuesto|ahorros?|economia|cuentas',
    health: 'salud|sueno|pasos|bienestar',
    sleepQ: 'como (?:he )?dormido|como dormi|cuanto (?:he )?dormido|que tal dormi',
    free: 'libre*|huecos?|disponibilidad|cuando puedo|cuando tengo tiempo|tiempo libre|espacios? libres?',
    notif: 'notificacion*|avisos',
    profile: 'perfil|cuenta',
    priv: 'privad[oa]',
    pub: 'public[oa]',
    photo: 'foto|imagen|fotografia',
    dark: 'oscuro|oscura|dark|nocturno',
    light: 'claro|clara|light|diurno',
    themeN: 'modo|tema',
    month: 'mes',
    week: 'semana',
    dayN: 'dia|jornada',
    urgent: '(?:como )?urgente*',
    important: '(?:como )?importante*',
    spent: 'cuanto (?:he )?(?:gastado|gaste|ahorrado|ahorre|ganado)|cuanto gasto|cuanto estoy gastando',
    nowQ: 'que (?:debo|deberia|puedo|hago|tengo que|toca)(?: hacer)? (?:ahora|primero|ya)|por donde (?:empiezo|empezar|comienzo)|que hago ahora|cual es (?:mi )?(?:la )?(?:siguiente|proxima|principal) (?:tarea|prioridad)|tarea mas urgente|mi prioridad|que sigue',
    qHave: 'que (?:tengo|hay|tenemos|planes tengo)|que me espera|cual es mi agenda|que hay en',
    qWhen: 'a que hora (?:es|tengo|empieza)|cuando es|cuando tengo',
    due: 'vence|vencimiento|fecha limite|plazo|fecha de entrega',
    workhours: 'horario de trabajo|horas de trabajo|jornada laboral|trabajo de',
    briefing: 'resumen del dia|resumen de hoy|como es mi dia|que me espera hoy|briefing|resumen diario',
    resched: 'reprograma(?:r)? (?:las )?(?:sesiones|tareas|cosas) (?:saltadas|perdidas|pendientes|no hechas)|replanifica*',
    feel: 'me siento|estoy|hoy me siento|hoy estoy|ando',
    into: 'a|como|en|por',
    yes: '^(?:si|vale|claro|de acuerdo|ok|okay|dale|perfecto|confirmo|confirmado|adelante|hazlo|correcto|exacto|por supuesto|sip)$',
    no: '^(?:no|nada|olvidalo|dejalo|deja eso|para|basta|no gracias|mejor no)$',
    choose: 'elige tu|decide tu|como prefieras|lo que prefieras|cuando quieras|a tu eleccion|tu eliges|escoge tu|a tu criterio|cuando te venga bien|cuando mejor te venga|lo que te venga mejor',
    apply: '^(?:aplica|aplicar|confirma|confirmar|aplicalo)$',
    keepboth: '^(?:mantener ambos|conserva ambos|deja ambos|quedate con ambos|ambos|los dos)$',
    help: 'ayuda|que sabes hacer|que puedes hacer|comandos|ejemplos|como funcionas',
    hello: '^(?:hola|buenas|buenos dias|buenas tardes|buenas noches|hey|que tal)$',
    thanks: '^(?:gracias|muchas gracias|vale gracias|genial|perfecto gracias)$',
  },
  pages: {
    home: 'inicio|pagina principal|home', plan: 'plan|calendario|agenda', tasks: 'tareas|pendientes', notes: 'notas', drive: 'drive|archivos', health: 'salud', finance: 'finanzas|dinero',
    travel: 'viajes', network: 'trabajo|red|empleos', profile: 'perfil', settings: 'ajustes|configuracion', mood: 'animo|estado de animo', messages: 'mensajes', notifications: 'notificaciones',
    stocks: 'acciones|bolsa', portfolio: 'cartera', taxes: 'impuestos', forecast: 'previsiones|pronostico', chat: 'chat',
  },
  moods: {
    happy: 'feliz|contento|contenta|alegre|bien|genial', calm: 'tranquil[oa]|calmad[oa]|sereno|serena|relajad[oa]', neutral: 'neutral|normal|regular',
    stressed: 'estresad[oa]|agobiad[oa]|nervios[oa]|ansios[oa]|preocupad[oa]', sad: 'triste|deprimid[oa]|mal|decaid[oa]', tired: 'cansad[oa]|agotad[oa]', angry: 'enfadad[oa]|enojad[oa]|molest[oa]',
  },
  withP: '(?:con|a|para) (?<p>\\p{L}[\\p{L}\\.\'-]*)',
  edge: 'a|al|a la|en|el|la|los|las|un|una|de|del|para|con|que|mi|mis|y|por|este|esta|lo|me|te|se',
};
