import type { LexData } from '../types.ts';

const r = String.raw;
const T = r`(?:a|vers|pour)`;
const AP = r`(?<ap>du matin|de l'apres-midi|de l'apres midi|du soir|de la nuit|am|pm|a\.m\.|p\.m\.)?`;

export const fr: LexData = {
  code: 'fr', script: 'latin', spaced: true,
  nums: { un: 1, une: 1, deux: 2, trois: 3, quatre: 4, cinq: 5, six: 6, sept: 7, huit: 8, neuf: 9, dix: 10, onze: 11, douze: 12, quinze: 15, vingt: 20, trente: 30 },
  today: r`aujourd'hui|ce soir|cette nuit|ce matin|cet apres-midi|cet apres midi`, tomorrow: 'demain', dayafter: r`apres-demain|apres demain`, yesterday: 'hier',
  weekdays: ['dimanche*', 'lundi*', 'mardi*', 'mercredi*', 'jeudi*', 'vendredi*', 'samedi*'],
  months: ['janvier', 'fevrier', 'mars', 'avril', 'mai', 'juin', 'juillet', 'aout', 'septembre', 'octobre', 'novembre', 'decembre'],
  nextweek: r`(?:la )?semaine prochaine`, thisweek: 'cette semaine',
  every: r`chaque|tous les|toutes les`,
  dayWord: 'jour|jours', weekWord: 'semaine|semaines',
  inN: [r`(?:dans|d'ici) (?<n>{num}) (?<u>jours?|semaines?|mois)`],
  unitDay: 'jour*', unitWeek: 'semaine*', unitMonth: 'mois',
  dates: [r`(?:le |pour le )?(?<d>\d{1,2})(?:er)? {mo}(?: \d{4})?`],
  time: [
    r`${T} (?<h>{num})\s*(?:h|heures?|:)\s*(?<m>\d{2})\s*${AP}`,
    r`${T} (?<h>{num})\s*(?:h|heures?)\s*et\s*(?:(?<half>demie?)|(?<qa>quart))\s*${AP}`,
    r`${T} (?<h>{num})\s*(?:h|heures?)\s*moins\s*(?:le\s*)?(?<qb>quart)\s*${AP}`,
    r`${T} (?<h>{num})\s*(?:h|heures?)\s*${AP}`,
    r`(?<h>\d{1,2})\s*(?:h|:)\s*(?<m>\d{2})`,
    r`(?<h>\d{1,2})\s*h`,
    r`(?<h>\d{1,2})\s*(?<ap>am|pm)`,
  ],
  range: [
    r`(?:de|entre|depuis) (?<h1>\d{1,2})\s*(?:h|:)?\s*(?<m1>\d{2})?\s*(?:a|et|jusqu'a) (?<h2>\d{1,2})\s*(?:h|:)?\s*(?<m2>\d{2})?`,
  ],
  dur: [r`(?:pendant|durant|pour|pour une duree de) (?<n>{num}|\d+(?:[.,]\d+)?)\s*(?<u>heures?|h|minutes?|min)`],
  unitHour: 'heure*|h', unitMin: 'minute*|min',
  halfHour: r`(?:pendant |pour )?(?:une )?demi-heure|demi heure`, oneHour: r`(?:pendant |pour )une heure`,
  pm: r`pm|p\.m\.|de l'apres-midi|de l'apres midi|du soir|de la nuit`, am: r`am|a\.m\.|du matin`,
  noon: 'midi', midnight: 'minuit',
  hintMorning: r`matin|matinee`, hintAfternoon: r`apres-midi|apres midi`, hintEvening: r`soir|soiree`,
  c: {
    polite: r`s'il te plait|s'il vous plait|stp|svp|peux-tu|peux tu|pourrais-tu|pourrais tu|pourrais|tu peux|vous pouvez|je veux|je voudrais|j'aimerais|j'ai besoin de|dis-moi|dis moi|hey|j'ai|je dois`,
    add: r`ajoute*|ajouter|rajoute*|cree|creer|cree-moi|mets|mettre|mets-moi|noter|inscris|inscrire|programme|programmer|planifie|planifier|reserve*|fixe|fixer|nouveau|nouvelle|rappelle-moi de|rappelle-moi|rappelle moi`,
    del: r`supprime*|efface*|enleve*|retire*|annule*|elimine*|ote|vire`,
    move: r`deplace*|decale*|repousse*|reporte*|reprogramme*|avance*|change(?:r)? (?:l'|la |le )?(?:heure|jour|date)|modifie(?:r)? (?:l'|la |le )?(?:heure|jour|date)`,
    done: r`j'ai fini|j'ai termine|j'ai fait|j'ai complete|c'est fait|c'est termine|fini|termine|marque(?:r)? (?:comme )?(?:fait|termine|finie?|accompli)\p{L}*|coche*|valide*`,
    show: r`montre*|affiche*|dis-moi|dis moi|liste*|donne-moi|donne moi|voir|quels sont|quelles sont|enumere*|consulte*|verifie*`,
    open: r`ouvre|ouvrir|va a|aller a|emmene-moi a|emmene moi a|affiche-moi|montre-moi|passe a`,
    rename: r`renomme*|change(?:r)? (?:le )?(?:nom|titre)(?: de)?`,
    share: r`partage*|envoie*|envoyer|transmets`,
    mark: r`marque*|mets|met|definis|regle|passe en|rends|rendre`,
    plan: r`planifie*|organise*|remplis*|arrange*|programme`,
    write: r`ecris*|note|noter|enregistre*|sauvegarde*|redige*|cree`,
    on: r`active*|allume*|autorise*|mets`,
    off: r`desactive*|coupe*|eteins*|bloque*|arrete*`,
    undo: r`^(?:annule|annule ca|annule tout|annule le dernier|annuler|defaire|defais|revenir en arriere|reviens en arriere|annule cela)$`,
    task: r`tache*|a faire|todo|to do|pense-bete`,
    event: r`reunion*|rdv|rendez-vous|rendez vous|evenement*|appel*|visioconference|entrainement|entretien|visite|diner|dejeuner|repas|cours|consultation|seance|seminaire`,
    cal: r`mon planning|planning|mon agenda|agenda|calendrier|mon calendrier|mon plan|le plan|au plan|emploi du temps`,
    note: r`note*|memo`,
    goal: r`objectif*|but`,
    mood: r`humeur|moral`,
    finance: r`finance*|depenses?|argent|budget|epargne|comptes?`,
    health: r`sante|sommeil|bien-etre`,
    sleepQ: r`comment (?:est-ce que )?j'ai dormi|comment j'ai dormi|combien (?:ai-je|j'ai) dormi`,
    free: r`libre*|creneaux?|disponibilite*|quand puis-je|temps libre`,
    notif: r`notification*|alerte*`,
    profile: r`profil|compte`,
    priv: r`prive*|privee`,
    pub: r`public*|publique`,
    photo: r`photo|image`,
    dark: r`sombre|dark|nuit`,
    light: r`clair|claire|light|jour`,
    themeN: r`mode|theme`,
    month: 'mois',
    week: 'semaine',
    dayN: r`journee|jour`,
    urgent: r`(?:comme )?urgent*`,
    important: r`(?:comme )?important*`,
    spent: r`combien (?:ai-je|j'ai|est-ce que j'ai) (?:depense|economise|gagne|epargne)|combien je depense|combien j'ai depense`,
    nowQ: r`que (?:dois-je|dois je|devrais-je|puis-je)(?: faire)? (?:maintenant|d'abord|en premier)|qu'est-ce que je dois faire (?:maintenant|d'abord)|par ou (?:commencer|je commence)|quelle est ma (?:prochaine|principale) (?:tache|priorite)|que faire maintenant|ma priorite`,
    qHave: r`qu'est-ce que j'ai|qu'ai-je|quel est mon programme|qu'est-ce qui est prevu|qu'est-ce qu'il y a|quels sont mes|j'ai quoi|qu'est-ce que j'ai de prevu`,
    qWhen: r`a quelle heure (?:est|ai-je|j'ai|commence)|quand (?:est|ai-je|j'ai)`,
    due: r`echeance|date limite|delai`,
    workhours: r`horaires? de travail|heures de travail|je travaille de|temps de travail`,
    briefing: r`resume de la journee|resume du jour|resume quotidien|ma journee|que m'attend-il aujourd'hui|briefing|bilan du jour`,
    resched: r`(?:replanifie\p{L}*|reprogramme\p{L}*) (?:les )?(?:sessions|taches|choses) (?:sautees|manquees|en retard|non faites)`,
    feel: r`je me sens|je suis|aujourd'hui je suis`,
    into: r`en|a|comme|par`,
    yes: r`^(?:oui|ouais|ok|d'accord|bien sur|parfait|je confirme|confirme|vas-y|fais-le|exactement|volontiers|c'est ca)$`,
    no: r`^(?:non|rien|laisse tomber|oublie|stop|ca suffit|non merci|plutot pas)$`,
    choose: r`choisis toi|decide toi|comme tu veux|comme tu preferes|quand tu veux|a toi de choisir|c'est toi qui choisis|choisis pour moi|quand ca t'arrange|a ton avis|ce qui t'arrange`,
    apply: r`^(?:applique|appliquer|confirme|confirmer|applique-le)$`,
    keepboth: r`^(?:garde les deux|garder les deux|garde-les tous les deux|les deux|garde tout)$`,
    help: r`aide|que sais-tu faire|que peux-tu faire|commandes|exemples|comment ca marche`,
    hello: r`^(?:bonjour|salut|coucou|bonsoir|hey|allo)$`,
    thanks: r`^(?:merci|merci beaucoup|super|parfait merci|genial)$`,
  },
  pages: {
    home: r`accueil|home`, plan: r`planning|agenda|calendrier`, tasks: 'taches', notes: 'notes', health: 'sante', finance: r`finances?|argent`, travel: r`voyages?`,
    network: r`travail|reseau|emplois`, profile: 'profil', settings: r`reglages|parametres`, mood: 'humeur', messages: 'messages', notifications: 'notifications',
    stocks: r`actions|bourse`, portfolio: 'portefeuille', taxes: 'impots', forecast: 'previsions', chat: 'chat',
  },
  moods: {
    happy: r`heureu(?:x|se)|content*|joyeu(?:x|se)|bien|super|genial`, calm: r`calme|serein*|tranquille|detendu*|zen`, neutral: r`neutre|normal*|moyen*`,
    stressed: r`stress*|anxieu*|nerveu*|angoisse*|inquiet*|tendu*`, sad: r`triste|deprim*|mal|abattu*`, tired: r`fatigu*|epuis*|crev*`, angry: r`en colere|furieu*|enerve*|agace*`,
  },
  withP: r`(?:avec|a|pour) (?<p>\p{L}[\p{L}'.-]*)`,
  edge: r`a|au|aux|en|le|la|les|un|une|de|du|des|pour|avec|que|mon|ma|mes|et|par|ce|cet|cette|me|te|se|dans|sur|lui`,
};
