import type { LexData } from '../types.ts';

const r = String.raw;
const T = r`(?:jam|pukul|sekitar jam|sekitar pukul|pada jam|pada pukul)`;
const AP = r`(?<ap>pagi|siang|sore|malam|dini hari|am|pm)?`;

export const id: LexData = {
  code: 'id', script: 'latin', spaced: true,
  nums: { satu: 1, dua: 2, tiga: 3, empat: 4, lima: 5, enam: 6, tujuh: 7, delapan: 8, sembilan: 9, sepuluh: 10, sebelas: 11, 'dua belas': 12, 'lima belas': 15, 'dua puluh': 20, 'tiga puluh': 30 },
  today: r`hari ini|malam ini|sore ini|pagi ini|siang ini|nanti malam|nanti sore`, tomorrow: 'besok', dayafter: 'lusa', yesterday: 'kemarin',
  weekdays: [r`hari minggu`, r`(?:hari )?senin`, r`(?:hari )?selasa`, r`(?:hari )?rabu`, r`(?:hari )?kamis`, r`(?:hari )?(?:jumat|jum'at)`, r`(?:hari )?sabtu`],
  months: ['januari', 'februari', 'maret', 'april', 'mei', 'juni', 'juli', 'agustus', 'september', 'oktober', 'november', 'desember'],
  nextweek: r`minggu depan|pekan depan|minggu berikutnya`, thisweek: r`minggu ini|pekan ini`,
  every: r`setiap|tiap`,
  dayWord: 'hari', weekWord: r`minggu|pekan`,
  inN: [r`(?<n>{num}) (?<u>hari|minggu|pekan|bulan) (?:lagi|ke depan|dari sekarang)`, r`dalam (?<n>{num}) (?<u>hari|minggu|pekan|bulan)`],
  unitDay: 'hari', unitWeek: r`minggu|pekan`, unitMonth: 'bulan',
  dates: [r`(?:tanggal |tgl\.? |pada tanggal )?(?<d>\d{1,2}) {mo}(?: \d{4})?`],
  time: [
    r`${T} (?<h>{num})[:.](?<m>\d{2})\s*${AP}`,
    r`${T} setengah (?<hb>{num})\s*${AP}`,
    r`${T} (?<h>{num})\s*${AP}`,
    r`(?<h>\d{1,2}):(?<m>\d{2})`,
  ],
  range: [r`(?:dari|antara) (?:jam |pukul )?(?<h1>\d{1,2})(?:[:.](?<m1>\d{2}))?\s*(?:sampai|hingga|ke|s/d|-)\s*(?:jam |pukul )?(?<h2>\d{1,2})(?:[:.](?<m2>\d{2}))?\s*(?<ap2>pagi|siang|sore|malam)?`],
  dur: [r`(?:selama|durasi|untuk|sekitar) (?<n>{num}|\d+(?:[.,]\d+)?) (?<u>jam|menit)`],
  unitHour: 'jam', unitMin: 'menit',
  halfHour: r`(?:selama )?setengah jam`, oneHour: r`(?:selama |untuk )?satu jam|sejam`,
  pm: r`sore|malam|siang|pm`, am: r`pagi|dini hari|am`,
  noon: r`tengah hari`, midnight: r`tengah malam`,
  hintMorning: r`pagi hari|pagi`, hintAfternoon: r`siang hari|sore hari|siang|sore`, hintEvening: r`malam hari|malam`,
  c: {
    polite: r`tolong|mohon|bisakah|bisa|dapatkah|saya mau|saya ingin|aku mau|aku ingin|saya perlu|aku perlu|ayo|hei|dong|deh|yuk|kasih tahu`,
    add: r`tambah*|tambahkan|buat|buatkan|masukkan|catat|catatkan|jadwalkan|atur|pasang|ingatkan saya untuk|ingatkan aku untuk|ingatkan|baru`,
    del: r`hapus*|hapuskan|buang|batalkan|singkirkan|cabut|delete`,
    move: r`pindah*|pindahkan|ubah (?:jam|waktu|hari|tanggal|jadwal)|ganti (?:jam|waktu|hari|tanggal)|undur*|majukan|tunda*|jadwal ulang`,
    done: r`(?:saya |aku )?(?:sudah|telah) (?:selesai|selesaikan|kerjakan|lakukan)|selesai|saya sudah|aku sudah|tandai (?:sebagai )?selesai|centang|beres|rampung`,
    show: r`tampilkan|tunjukkan|lihat|beritahu|sebutkan|daftar*|apa saja|apa yang|berikan|cek|periksa`,
    open: r`buka*|bukakan|pergi ke|ke halaman|antar saya ke`,
    rename: r`ganti nama|ubah nama|rename|namai ulang|ganti judul|ubah judul`,
    share: r`bagikan|kirim*|bagi|share`,
    mark: r`tandai|jadikan|setel|set|ubah jadi|ubah menjadi`,
    plan: r`rencanakan|susun|isi|jadwalkan|susunkan|aturkan`,
    write: r`tulis*|catat*|simpan|bikin`,
    on: r`aktifkan|nyalakan|hidupkan|izinkan`,
    off: r`matikan|nonaktifkan|blokir|bisukan|hentikan`,
    undo: r`^(?:batalkan|batalkan itu|urungkan|kembalikan|undo|batal|mundur|batalkan yang terakhir|batalkan terakhir)$`,
    task: r`tugas*|to-?do|todo|pekerjaan|kerjaan|daftar tugas`,
    event: r`rapat|pertemuan|janji|acara|panggilan|telepon|video call|latihan|wawancara|kunjungan|makan malam|makan siang|kelas|konsultasi|sesi|seminar|meeting|kegiatan`,
    cal: r`rencana saya|rencanaku|rencana|kalender|agenda|jadwal saya|jadwalku|jadwal|kalender saya`,
    note: r`catatan|memo|notes?`,
    goal: r`tujuan|target|sasaran`,
    mood: r`suasana hati|mood|perasaan`,
    finance: r`keuangan|pengeluaran|uang|anggaran|budget|tabungan|rekening|finansial`,
    health: r`kesehatan|tidur|langkah|kebugaran`,
    sleepQ: r`bagaimana tidur saya|gimana tidur saya|berapa lama saya tidur|bagaimana saya tidur`,
    free: r`kosong|luang|senggang|waktu luang|kapan saya bisa|kapan saya kosong|kapan saya luang|slot kosong|jam kosong|tersedia`,
    notif: r`notifikasi|pemberitahuan`,
    profile: r`profil|akun`,
    priv: r`privat|pribadi`,
    pub: r`publik|umum`,
    photo: r`foto|gambar`,
    dark: r`gelap|dark`,
    light: r`terang|light`,
    themeN: r`mode|tema`,
    month: 'bulan',
    week: r`minggu|pekan`,
    dayN: r`hari|harian`,
    urgent: r`(?:sebagai )?(?:mendesak|urgent)`,
    important: r`(?:sebagai )?penting`,
    spent: r`berapa (?:banyak )?(?:uang )?(?:yang )?(?:saya )?(?:habiskan|keluarkan|hemat|tabung|dapat)|berapa pengeluaran saya|berapa saya (?:menghabiskan|mengeluarkan|berhemat)`,
    nowQ: r`apa yang (?:harus|sebaiknya|bisa) (?:saya )?(?:lakukan|kerjakan) (?:sekarang|dulu|pertama)|harus (?:ngapain|apa) sekarang|mulai dari mana|apa tugas (?:saya )?(?:berikutnya|selanjutnya|utama)|prioritas saya|sekarang (?:harus )?ngapain`,
    qHave: r`apa (?:saja )?(?:yang )?(?:ada|saya punya)|ada apa|apa jadwal|jadwal apa|apa rencana|ada acara apa|apa yang menunggu`,
    qWhen: r`jam berapa|pukul berapa|kapan`,
    due: r`tenggat|batas waktu|deadline|jatuh tempo`,
    workhours: r`jam kerja|waktu kerja|saya bekerja dari|aku kerja dari`,
    briefing: r`ringkasan hari ini|ringkasan harian|bagaimana hari saya|apa yang menunggu hari ini|briefing|rangkuman hari ini`,
    resched: r`jadwalkan ulang (?:sesi|tugas) (?:yang )?(?:terlewat|terlewatkan|tertunda|dilewati)|atur ulang (?:sesi|tugas) yang terlewat`,
    feel: r`saya merasa|aku merasa|saya sedang|aku lagi|hari ini saya|aku sedang|saya lagi|merasa`,
    into: r`menjadi|jadi|ke|dengan`,
    yes: r`^(?:ya|iya|oke|ok|baik|boleh|setuju|tentu|betul|benar|siap|lakukan|silakan|yup|sip)$`,
    no: r`^(?:tidak|nggak|enggak|ga|gak|jangan|lupakan|biarkan|stop|cukup|tidak usah|nggak usah|tidak jadi)$`,
    choose: r`pilih saja|kamu pilih|anda pilih|terserah|terserah kamu|terserah kamu saja|kapan saja|sesukamu|yang paling nyaman|yang cocok|atur saja|kamu yang tentukan|tentukan saja`,
    apply: r`^(?:terapkan|konfirmasi|jalankan|terapkan saja)$`,
    keepboth: r`^(?:pertahankan keduanya|simpan keduanya|keduanya|dua-duanya|dua duanya)$`,
    help: r`bantuan|bantu|apa yang bisa kamu lakukan|apa yang bisa kamu|perintah|contoh|cara kerja`,
    hello: r`^(?:halo|hai|hi|selamat pagi|selamat siang|selamat sore|selamat malam|hei|hello)$`,
    thanks: r`^(?:terima kasih|makasih|thanks|terimakasih|trims|terima kasih banyak|thx)$`,
  },
  pages: {
    home: r`beranda|home|halaman utama`, plan: r`rencana|kalender|agenda|jadwal`, tasks: 'tugas', notes: 'catatan', health: 'kesehatan', finance: 'keuangan', travel: r`perjalanan|liburan`,
    network: r`pekerjaan|jaringan|lowongan`, profile: 'profil', settings: 'pengaturan', mood: r`suasana hati|mood`, messages: 'pesan', notifications: 'notifikasi',
    stocks: 'saham', portfolio: 'portofolio', taxes: 'pajak', forecast: r`prakiraan|prediksi`, chat: r`obrolan|chat`,
  },
  moods: {
    happy: r`senang|bahagia|gembira|baik|bagus|riang|puas`, calm: r`tenang|santai|damai|rileks`, neutral: r`biasa saja|netral|biasa`,
    stressed: r`stres|stress|tertekan|cemas|gelisah|khawatir|panik|gugup`, sad: r`sedih|murung|galau|buruk|kecewa`, tired: r`lelah|capek|letih|kecapekan|capai`, angry: r`marah|kesal|jengkel|emosi`,
  },
  withP: r`(?:dengan|kepada|ke|untuk) (?<p>\p{L}[\p{L}'.-]*)`,
  edge: r`ke|di|dari|pada|untuk|dengan|dan|yang|ini|itu|saya|aku|ku|kamu|ya|dong|nih|lah|tolong|ada|sebagai|akan|atau|bisa`,
};
