import type { LexData } from '../types.ts';

const r = String.raw;
const T = r`(?:às|à|a|ao|por volta das|pelas|para as|as)`;
const AP = r`(?<ap>da manhã|da tarde|da noite|da madrugada|am|pm|a\.m\.|p\.m\.)?`;

export const pt: LexData = {
  code: 'pt', script: 'latin', spaced: true,
  nums: { um: 1, uma: 1, dois: 2, duas: 2, três: 3, tres: 3, quatro: 4, cinco: 5, seis: 6, sete: 7, oito: 8, nove: 9, dez: 10, onze: 11, doze: 12, quinze: 15, vinte: 20, trinta: 30 },
  today: r`hoje|hoje à noite|hoje de manhã|hoje à tarde|esta noite|esta tarde|esta manhã`, tomorrow: 'amanhã', dayafter: 'depois de amanhã', yesterday: 'ontem',
  weekdays: ['domingo*', r`segunda(?:-feira| feira)?`, r`terça(?:-feira| feira)?`, r`quarta(?:-feira| feira)?`, r`quinta(?:-feira| feira)?`, r`sexta(?:-feira| feira)?`, 'sábado*'],
  months: ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'],
  nextweek: r`(?:na )?semana que vem|(?:na )?próxima semana`, thisweek: 'esta semana',
  every: r`todas as|todos os|toda|todo|todas|todos|cada`,
  dayWord: 'dia|dias', weekWord: 'semana|semanas',
  inN: [r`(?:daqui a|dentro de|em) (?<n>{num}) (?<u>dias?|semanas?|meses|mês)`],
  unitDay: 'dia*', unitWeek: 'semana*', unitMonth: r`mes|meses|mês`,
  dates: [r`(?:no |para o |dia )?(?<d>\d{1,2}) (?:de )?{mo}(?: de \d{4})?`],
  time: [
    r`${T} (?<h>{num})(?::|h)(?<m>\d{2})\s*${AP}`,
    r`${T} (?<h>{num})\s*(?:h|horas?)?\s*e\s*(?:(?<half>meia)|(?<qa>um quarto|quinze))\s*${AP}`,
    r`${T} (?<h>{num})\s*(?:h|horas?)?\s*menos\s*(?<qb>um quarto|quinze)\s*${AP}`,
    r`${T} (?<h>{num})\s*(?:h|horas?|em ponto)?\s*${AP}`,
    r`(?<h>\d{1,2})(?::|h)(?<m>\d{2})`,
    r`(?<h>\d{1,2})\s*h`,
    r`(?<h>\d{1,2})\s*(?<ap>am|pm)`,
  ],
  range: [r`(?:das|de|entre) (?<h1>\d{1,2})(?:(?::|h)(?<m1>\d{2}))?\s*h?\s*(?:às|as|a|até as|até|e) (?<h2>\d{1,2})(?:(?::|h)(?<m2>\d{2}))?\s*h?`],
  dur: [r`(?:por|durante) (?<n>{num}|\d+(?:[.,]\d+)?) (?<u>horas?|h|minutos?|min)`],
  unitHour: 'hora*|h', unitMin: 'minuto*|min',
  halfHour: r`(?:por |durante )?meia hora`, oneHour: r`(?:por |durante )?uma hora`,
  pm: r`pm|p\.m\.|da tarde|da noite`, am: r`am|a\.m\.|da manhã|da madrugada`,
  noon: r`meio[- ]dia`, midnight: r`meia[- ]noite`,
  hintMorning: r`de manhã|pela manhã|da manhã|esta manhã`, hintAfternoon: r`à tarde|pela tarde|da tarde|esta tarde|de tarde`, hintEvening: r`à noite|pela noite|da noite|esta noite|de noite`,
  c: {
    polite: r`por favor|pfv|pode|poderia|quero|queria|gostaria|preciso|me ajuda a|ei|oi|diga|vamos`,
    add: r`adiciona*|adicione|acrescenta*|anota*|cria|criar|crie|coloca*|põe|poe|insere*|inclui*|agende|agendar|agenda (?:uma|um)|marcar|marque|programa*|reserva*|novo|nova|lembra* me de|lembre-me de|me lembra de`,
    del: r`apaga*|elimina*|remove*|exclui*|deleta*|tira*|cancela*|retira*|descarta*`,
    move: r`move*|mover|remarca*|reagenda*|adia*|antecipa*|transfere*|muda(?:r)? (?:a |o )?(?:hora|horário|dia|data)|altera(?:r)? (?:a |o )?(?:hora|horário|dia|data)`,
    done: r`terminei|concluí|completei|fiz|acabei|feito|concluído|concluída|completo|completa|marca* (?:como )?(?:feit[oa]|conclu\p{L}+|termina\p{L}+)|risca*|já fiz|já terminei|está feito`,
    show: r`mostra*|mostrar|me diz|diga|lista*|me dá|veja|ver|quais são|enumera*|consulta*|exibe*`,
    open: r`abre|abrir|abra|vai para|ir para|vá para|leva-me|me leva para|vamos para|entra em`,
    rename: r`renomeia*|renomear|muda(?:r)? (?:o )?(?:nome|título)(?: de)?|altera(?:r)? (?:o )?(?:nome|título)(?: de)?`,
    share: r`compartilha*|compartilhar|partilha*|envia*|manda*`,
    mark: r`marca*|coloca*|define*|configura*|deixa*|faz|torna*|poe|põe`,
    plan: r`planeja*|planejar|organiza*|preenche*|arruma*|programa*`,
    write: r`escreve*|anota*|salva*|guarda*|redige*|cria`,
    on: r`ativa*|liga*|habilita*|permite*`,
    off: r`desativa*|desliga*|desabilita*|silencia*|bloqueia*`,
    undo: r`^(?:desfaz|desfazer|desfaz isso|cancela isso|anula|anular|volta|voltar|reverte|reverter|desfaça)$`,
    task: r`tarefa*|pendência*|afazer*|a fazer|to do|todo|atividade*`,
    event: r`reunião|reuniões|compromisso*|evento*|ligação|ligações|chamada*|videochamada*|treino*|entrevista|visita|jantar|almoço|consulta|aula|encontro|sessão|seminário`,
    cal: r`meu plano|o plano|plano|calendário|agenda|minha agenda|meu calendário|horário|cronograma`,
    note: r`nota*|anotação|anotações|memorando`,
    goal: r`objetivo*|meta*`,
    mood: r`humor|estado de espírito|ânimo`,
    finance: r`finanças|financeiro|despesa*|gasto*|dinheiro|orçamento|poupança|economia|contas`,
    health: r`saúde|sono|passos|bem-estar`,
    sleepQ: r`como (?:eu )?dormi|quanto (?:eu )?dormi|como foi meu sono`,
    free: r`livre*|vaga*|brecha*|disponib\p{L}+|quando posso|quando tenho tempo|tempo livre|horários livres`,
    notif: r`notificaç\p{L}+|avisos|alertas`,
    profile: r`perfil|conta`,
    priv: r`privad[oa]`,
    pub: r`public[oa]|pública`,
    photo: r`foto|imagem|fotografia`,
    dark: r`escuro|escura|dark|noturno`,
    light: r`claro|clara|light|diurno`,
    themeN: r`modo|tema`,
    month: 'mês',
    week: 'semana',
    dayN: r`dia|jornada`,
    urgent: r`(?:como )?urgente*`,
    important: r`(?:como )?importante*`,
    spent: r`quanto (?:eu )?(?:gastei|economizei|poupei|ganhei)|quanto gasto|quanto estou gastando`,
    nowQ: r`o que (?:devo|eu devo|posso|faço|preciso|tenho que)(?: fazer)? (?:agora|primeiro|já)|por onde (?:começo|começar)|o que faço agora|qual (?:é )?(?:a )?(?:minha )?(?:próxima|principal) (?:tarefa|prioridade)|tarefa mais urgente|minha prioridade|o que vem agora`,
    qHave: r`o que (?:eu )?tenho|o que (?:tem|há)|quais são meus compromissos|o que está marcado|o que me espera|qual é a minha agenda`,
    qWhen: r`a que horas (?:é|tenho|começa)|que horas (?:é|tenho|começa)|quando (?:é|tenho)`,
    due: r`vence|vencimento|prazo|data limite|data de entrega`,
    workhours: r`horário de trabalho|horas de trabalho|jornada de trabalho|eu trabalho das|trabalho das`,
    briefing: r`resumo do dia|resumo de hoje|como está meu dia|o que me espera hoje|briefing|resumo diário`,
    resched: r`reagenda\p{L}* (?:as )?(?:sessões|tarefas|coisas) (?:puladas|perdidas|pendentes|não feitas)|replaneja*`,
    feel: r`me sinto|estou|hoje me sinto|hoje estou`,
    into: r`para|como|em|por`,
    yes: r`^(?:sim|claro|ok|okay|certo|pode ser|combinado|perfeito|confirmo|confirmado|vai|faz isso|exato|com certeza|beleza|isso mesmo)$`,
    no: r`^(?:não|nada|esquece|deixa|deixa pra lá|para|chega|não obrigado|melhor não)$`,
    choose: r`escolhe você|decide você|como preferir|quando quiser|a sua escolha|você escolhe|escolha você|como você quiser|quando for melhor|quando for mais conveniente|quando te convier`,
    apply: r`^(?:aplica|aplicar|confirma|confirmar|aplique)$`,
    keepboth: r`^(?:manter ambos|mantém ambos|deixa ambos|fica com ambos|ambos|os dois)$`,
    help: r`ajuda|o que você sabe fazer|o que você pode fazer|comandos|exemplos|como funciona`,
    hello: r`^(?:olá|oi|bom dia|boa tarde|boa noite|e aí|opa|oie)$`,
    thanks: r`^(?:obrigado|obrigada|muito obrigado|muito obrigada|valeu|show|ótimo obrigado)$`,
  },
  pages: {
    home: r`início|página inicial|home`, plan: r`plano|calendário|agenda`, tasks: r`tarefas|pendências`, notes: 'notas', health: 'saúde', finance: r`finanças|dinheiro`, travel: 'viagens',
    network: r`trabalho|rede|empregos`, profile: 'perfil', settings: r`ajustes|configurações`, mood: r`humor|estado de espírito`, messages: 'mensagens', notifications: 'notificações',
    stocks: r`ações|bolsa`, portfolio: 'carteira', taxes: 'impostos', forecast: 'previsões', chat: 'chat',
  },
  moods: {
    happy: r`feliz|contente|alegre|bem|ótimo|animad[oa]`, calm: r`tranquil[oa]|calm[oa]|sereno|serena|relaxad[oa]`, neutral: r`neutro|neutra|normal|mais ou menos`,
    stressed: r`estressad[oa]|nervos[oa]|ansios[oa]|preocupad[oa]|sobrecarregad[oa]`, sad: r`triste|deprimid[oa]|mal|abatid[oa]`, tired: r`cansad[oa]|exausto|exausta`, angry: r`bravo|brava|irritad[oa]|com raiva|furios[oa]`,
  },
  withP: r`(?:com|para|a) (?<p>\p{L}[\p{L}'.-]*)`,
  edge: r`a|as|o|os|um|uma|uns|umas|de|do|da|dos|das|em|no|na|nos|nas|para|pra|com|que|meu|minha|meus|minhas|e|por|ao|aos|me|te|se|este|esta|isso`,
};
